import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type AppLanguage = 'en' | 'bn';

const STORAGE_KEY = 'sbms_language';

const BN_TRANSLATIONS: Record<string, string> = {
  English: 'English',
  'বাংলা': 'বাংলা',
  Language: 'ভাষা',
  Notifications: 'নোটিফিকেশন',
  Messages: 'মেসেজ',
  'No new alerts': 'নতুন অ্যালার্ট নেই',
  'No live messages yet': 'কোনো লাইভ মেসেজ নেই',
  'Open related page': 'সংশ্লিষ্ট পেজ খুলুন',
  'Banking Management System': 'ব্যাংকিং ম্যানেজমেন্ট সিস্টেম',
  'Shariah-Compliant ERP': 'শরীয়াহ-কমপ্লায়েন্ট ERP',
  'SBMS Core Banking Operations. All rights reserved.': 'SBMS কোর ব্যাংকিং অপারেশনস। সর্বস্বত্ব সংরক্ষিত।',
  'Core services monitored': 'কোর সার্ভিস মনিটরড',
  'Regulatory reporting enabled': 'রেগুলেটরি রিপোর্টিং সক্রিয়',
  'Secured Portal': 'সিকিউরড পোর্টাল',
  'Compliance Ready': 'কমপ্লায়েন্স রেডি',
  'Global Search': 'গ্লোবাল সার্চ',
  'No matching page found': 'মিল পাওয়া যায়নি',
  'Search pages, modules, actions...': 'পেজ, মডিউল, অ্যাকশন খুঁজুন...',
  'Current time': 'বর্তমান সময়',
  'Switch to light mode': 'লাইট মোডে যান',
  'Switch to dark mode': 'ডার্ক মোডে যান',
  'My Profile': 'আমার প্রোফাইল',
  'Change Password': 'পাসওয়ার্ড পরিবর্তন',
  'Sign Out': 'সাইন আউট',
  Home: 'হোম',
  Filter: 'ফিল্টার',
  'Refine records before viewing or exporting data.': 'ডাটা দেখার বা এক্সপোর্ট করার আগে রেকর্ড ফিল্টার করুন।',
  View: 'দেখুন',
  Save: 'সংরক্ষণ',
  Update: 'আপডেট',
  Delete: 'ডিলিট',
  Edit: 'এডিট',
  Print: 'প্রিন্ট',
  Export: 'এক্সপোর্ট',
  Preview: 'প্রিভিউ',
  Download: 'ডাউনলোড',
  Submit: 'সাবমিট',
  Approve: 'অনুমোদন',
  Reject: 'রিজেক্ট',
  Close: 'বন্ধ',
  Assign: 'অ্যাসাইন',
  'Clear Filters': 'ফিল্টার ক্লিয়ার',
  'No data found': 'কোনো ডাটা পাওয়া যায়নি',
  'There is nothing to display here yet.': 'এখনো দেখানোর মতো ডাটা নেই।',
  GENERAL: 'সাধারণ',
  OPERATIONS: 'অপারেশনস',
  ADMINISTRATION: 'অ্যাডমিনিস্ট্রেশন',
  Dashboard: 'ড্যাশবোর্ড',
  'Branch Management': 'ব্রাঞ্চ ম্যানেজমেন্ট',
  'Customer Management': 'কাস্টমার ম্যানেজমেন্ট',
  'KYC Management': 'KYC ম্যানেজমেন্ট',
  'Account Management': 'অ্যাকাউন্ট ম্যানেজমেন্ট',
  'Transactions Management': 'ট্রানজেকশন ম্যানেজমেন্ট',
  'Card Management': 'কার্ড ম্যানেজমেন্ট',
  'Deposit Schemes Management': 'ডিপোজিট স্কিম ম্যানেজমেন্ট',
  'Profit Management': 'প্রফিট ম্যানেজমেন্ট',
  'Financing Management': 'ফাইন্যান্সিং ম্যানেজমেন্ট',
  'Contracts Management': 'কন্ট্রাক্ট ম্যানেজমেন্ট',
  'Shariah Review Management': 'শরীয়াহ রিভিউ ম্যানেজমেন্ট',
  'Zakat & Charity Management': 'যাকাত ও চ্যারিটি ম্যানেজমেন্ট',
  'Statements Generation': 'স্টেটমেন্ট জেনারেশন',
  'Reporting & Regulatory Compliance': 'রিপোর্টিং ও রেগুলেটরি কমপ্লায়েন্স',
  'Workflow Support Management': 'ওয়ার্কফ্লো সাপোর্ট ম্যানেজমেন্ট',
  'Verification Management': 'ভেরিফিকেশন ম্যানেজমেন্ট',
  'Security / Audit Management': 'সিকিউরিটি / অডিট ম্যানেজমেন্ট',
  'Notification & Alerts Management': 'নোটিফিকেশন ও অ্যালার্ট ম্যানেজমেন্ট',
  'Integration Management': 'ইন্টিগ্রেশন ম্যানেজমেন্ট',
  'ATM / CDM Management': 'ATM / CDM ম্যানেজমেন্ট',
  'Calculation Engine Management': 'ক্যালকুলেশন ইঞ্জিন ম্যানেজমেন্ট',
  'User Management': 'ইউজার ম্যানেজমেন্ট',
  'Role Management': 'রোল ম্যানেজমেন্ট',
  'Lookup / Config Management': 'লুকআপ / কনফিগ ম্যানেজমেন্ট',
  'Branch Dashboard': 'ব্রাঞ্চ ড্যাশবোর্ড',
  'Branch List': 'ব্রাঞ্চ লিস্ট',
  'Create Branch': 'নতুন ব্রাঞ্চ',
  'Branch Assignments': 'ব্রাঞ্চ অ্যাসাইনমেন্ট',
  'Teller Limits': 'টেলার লিমিট',
  'Vault Balance List': 'ভল্ট ব্যালেন্স লিস্ট',
  'Open Vault': 'ভল্ট ওপেন',
  'Cash Ledger': 'ক্যাশ লেজার',
  'Inter-Branch Transfer': 'ইন্টার-ব্রাঞ্চ ট্রান্সফার',
  'EOD Summary': 'EOD সামারি',
  'Customer Dashboard': 'কাস্টমার ড্যাশবোর্ড',
  'Customer List': 'কাস্টমার লিস্ট',
  'New Customer': 'নতুন কাস্টমার',
  'Customer Search': 'কাস্টমার সার্চ',
  'Status Action': 'স্ট্যাটাস অ্যাকশন',
  'KYC Dashboard': 'KYC ড্যাশবোর্ড',
  'KYC List': 'KYC লিস্ট',
  'New KYC Profile': 'নতুন KYC প্রোফাইল',
  'Approval Queue': 'অ্যাপ্রুভাল কিউ',
  'Account Dashboard': 'অ্যাকাউন্ট ড্যাশবোর্ড',
  'Account List': 'অ্যাকাউন্ট লিস্ট',
  'Opening Requests': 'ওপেনিং রিকোয়েস্ট',
  'New Opening Request': 'নতুন ওপেনিং রিকোয়েস্ট',
  'Account Types': 'অ্যাকাউন্ট টাইপ',
  'New Account Type': 'নতুন অ্যাকাউন্ট টাইপ',
  'Transaction Dashboard': 'ট্রানজেকশন ড্যাশবোর্ড',
  'Transaction Journal': 'ট্রানজেকশন জার্নাল',
  'Cash Deposit': 'ক্যাশ ডিপোজিট',
  'Cash Withdraw': 'ক্যাশ উইথড্র',
  'Fund Transfer': 'ফান্ড ট্রান্সফার',
  'Cheque Clearing': 'চেক ক্লিয়ারিং',
  'Standing Instructions': 'স্ট্যান্ডিং ইনস্ট্রাকশন',
  'New Standing Instruction': 'নতুন স্ট্যান্ডিং ইনস্ট্রাকশন',
  'Card Dashboard': 'কার্ড ড্যাশবোর্ড',
  'Card List': 'কার্ড লিস্ট',
  'Issue Card': 'কার্ড ইস্যু',
  'PIN Events': 'PIN ইভেন্ট',
  'ATM/CDM Usage': 'ATM/CDM ইউসেজ',
  'Scheme Dashboard': 'স্কিম ড্যাশবোর্ড',
  'Scheme List': 'স্কিম লিস্ট',
  'New Scheme': 'নতুন স্কিম',
  'Enrollment List': 'এনরোলমেন্ট লিস্ট',
  'New Enrollment': 'নতুন এনরোলমেন্ট',
  'Profit Dashboard': 'প্রফিট ড্যাশবোর্ড',
  'Profit Ratios': 'প্রফিট রেশিও',
  'New Profit Ratio': 'নতুন প্রফিট রেশিও',
  'Profit Schedules': 'প্রফিট শিডিউল',
  'New Profit Schedule': 'নতুন প্রফিট শিডিউল',
  'Profit Postings': 'প্রফিট পোস্টিং',
  'Run Profit Posting': 'প্রফিট পোস্টিং রান',
  'Financing Dashboard': 'ফাইন্যান্সিং ড্যাশবোর্ড',
  'Product List': 'প্রোডাক্ট লিস্ট',
  'New Product': 'নতুন প্রোডাক্ট',
  'Application List': 'অ্যাপ্লিকেশন লিস্ট',
  'New Application': 'নতুন অ্যাপ্লিকেশন',
  'Contract Dashboard': 'কন্ট্রাক্ট ড্যাশবোর্ড',
  'Template List': 'টেমপ্লেট লিস্ট',
  'New Template': 'নতুন টেমপ্লেট',
  'Contract List': 'কন্ট্রাক্ট লিস্ট',
  'Generate Contract': 'কন্ট্রাক্ট জেনারেট',
  'Shariah Dashboard': 'শরীয়াহ ড্যাশবোর্ড',
  'Case List': 'কেস লিস্ট',
  'Correction Queue': 'কারেকশন কিউ',
  'Fatwa Certificates': 'ফতোয়া সার্টিফিকেট',
  'Annual Report': 'বার্ষিক রিপোর্ট',
  'Zakat Dashboard': 'যাকাত ড্যাশবোর্ড',
  'Profile List': 'প্রোফাইল লিস্ট',
  'Run Zakat': 'যাকাত রান',
  'Charity Fund': 'চ্যারিটি ফান্ড',
  'Beneficiary List': 'বেনিফিশিয়ারি লিস্ট',
  'New Beneficiary': 'নতুন বেনিফিশিয়ারি',
  'Payout List': 'পেআউট লিস্ট',
  'New Payout': 'নতুন পেআউট',
  'Statement Dashboard': 'স্টেটমেন্ট ড্যাশবোর্ড',
  'Customer Requests': 'কাস্টমার রিকোয়েস্ট',
  'New Customer Statement': 'নতুন কাস্টমার স্টেটমেন্ট',
  'Branch Requests': 'ব্রাঞ্চ রিকোয়েস্ট',
  'New Branch Statement': 'নতুন ব্রাঞ্চ স্টেটমেন্ট',
  'Export Center': 'এক্সপোর্ট সেন্টার',
  'Report Dashboard': 'রিপোর্ট ড্যাশবোর্ড',
  'Operational Report': 'অপারেশনাল রিপোর্ট',
  'Profit Distribution': 'প্রফিট ডিস্ট্রিবিউশন',
  'Management P&L': 'ম্যানেজমেন্ট P&L',
  'Expense Register': 'এক্সপেন্স রেজিস্টার',
  'Trial Balance': 'ট্রায়াল ব্যালেন্স',
  'Ledger Profit & Loss': 'লেজার প্রফিট অ্যান্ড লস',
  'Financing Portfolio': 'ফাইন্যান্সিং পোর্টফোলিও',
  'PAR Report': 'PAR রিপোর্ট',
  'Shariah Audit': 'শরীয়াহ অডিট',
  'Branch Report': 'ব্রাঞ্চ রিপোর্ট',
  'Export History': 'এক্সপোর্ট হিস্টোরি',
  'Workflow Dashboard': 'ওয়ার্কফ্লো ড্যাশবোর্ড',
  'Pending Queue': 'পেন্ডিং কিউ',
  'My Submissions': 'আমার সাবমিশন',
  'Workflow History': 'ওয়ার্কফ্লো হিস্টোরি',
  'Verification Dashboard': 'ভেরিফিকেশন ড্যাশবোর্ড',
  'Verify OTP': 'OTP ভেরিফাই',
  'Verification Logs': 'ভেরিফিকেশন লগ',
  'Forgot Password': 'পাসওয়ার্ড ভুলে গেছি',
  'Reset Password': 'পাসওয়ার্ড রিসেট',
  'Provider Test Console': 'প্রোভাইডার টেস্ট কনসোল',
  'Security Dashboard': 'সিকিউরিটি ড্যাশবোর্ড',
  'Security Events': 'সিকিউরিটি ইভেন্ট',
  'Suspicious Activity': 'সাসপিশাস অ্যাক্টিভিটি',
  'Audit Logs': 'অডিট লগ',
  'Investigation Cases': 'ইনভেস্টিগেশন কেস',
  'Notification Dashboard': 'নোটিফিকেশন ড্যাশবোর্ড',
  'Event Rule List': 'ইভেন্ট রুল লিস্ট',
  'New Event Rule': 'নতুন ইভেন্ট রুল',
  'Delivery Logs': 'ডেলিভারি লগ',
  'Retry Queue': 'রিট্রাই কিউ',
  'Integration Dashboard': 'ইন্টিগ্রেশন ড্যাশবোর্ড',
  'Provider List': 'প্রোভাইডার লিস্ট',
  'New Provider': 'নতুন প্রোভাইডার',
  'Provider Test': 'প্রোভাইডার টেস্ট',
  'Execution Logs': 'এক্সিকিউশন লগ',
  'ATM Dashboard': 'ATM ড্যাশবোর্ড',
  'Terminal List': 'টার্মিনাল লিস্ট',
  'Cash Bin List': 'ক্যাশ বিন লিস্ট',
  'Cash Bin Setup': 'ক্যাশ বিন সেটআপ',
  'Replenishment List': 'রিপ্লেনিশমেন্ট লিস্ট',
  'New Replenishment': 'নতুন রিপ্লেনিশমেন্ট',
  'Reconciliation List': 'রিকনসিলিয়েশন লিস্ট',
  'New Reconciliation': 'নতুন রিকনসিলিয়েশন',
  'ATM/CDM Journal': 'ATM/CDM জার্নাল',
  'Calculation Dashboard': 'ক্যালকুলেশন ড্যাশবোর্ড',
  'Calculation Simulator': 'ক্যালকুলেশন সিমুলেটর',
  'User Dashboard': 'ইউজার ড্যাশবোর্ড',
  'User List': 'ইউজার লিস্ট',
  'New User': 'নতুন ইউজার',
  'Role Dashboard': 'রোল ড্যাশবোর্ড',
  'Role List': 'রোল লিস্ট',
  'New Role': 'নতুন রোল',
  'Lookup Dashboard': 'লুকআপ ড্যাশবোর্ড',
  'Lookup Types': 'লুকআপ টাইপ',
  'New Lookup Type': 'নতুন লুকআপ টাইপ',
  'Lookup Values': 'লুকআপ ভ্যালু',
  'New Lookup Value': 'নতুন লুকআপ ভ্যালু'
};

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private readonly languageSubject = new BehaviorSubject<AppLanguage>(this.readInitialLanguage());
  readonly language$ = this.languageSubject.asObservable();

  get currentLanguage(): AppLanguage {
    return this.languageSubject.value;
  }

  setLanguage(language: AppLanguage): void {
    this.languageSubject.next(language);
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.setAttribute('lang', language === 'bn' ? 'bn' : 'en');
  }

  translate(value?: string | null): string {
    const text = String(value || '');
    if (!text || this.currentLanguage === 'en') {
      return text;
    }
    return BN_TRANSLATIONS[text] || text;
  }

  private readInitialLanguage(): AppLanguage {
    const saved = localStorage.getItem(STORAGE_KEY);
    const language: AppLanguage = saved === 'bn' ? 'bn' : 'en';
    document.documentElement.setAttribute('lang', language === 'bn' ? 'bn' : 'en');
    return language;
  }
}
