-- Recommended default RBAC action matrix for the 7 canonical roles.
-- This script is additive: it inserts only missing permissions.

INSERT INTO role_permission (
    role_id,
    module_name,
    action_name,
    permission_code,
    display_name,
    allow_flag,
    created_at,
    created_by
)
SELECT
    r.id,
    seed.module_name,
    seed.action_name,
    seed.permission_code,
    seed.display_name,
    b'1',
    NOW(6),
    'RBAC_DEFAULT_MATRIX'
FROM roles r
JOIN (
    SELECT 'BRANCH_MANAGER' AS role_code, 'BRANCH_MANAGEMENT' AS module_name, 'ASSIGN_USER' AS action_name, 'BRANCH_ASSIGN_USER' AS permission_code, 'Branch Management - Assign Branch User' AS display_name
    UNION ALL SELECT 'BRANCH_MANAGER', 'BRANCH_MANAGEMENT', 'TELLER_LIMIT_MANAGE', 'BRANCH_TELLER_LIMIT_MANAGE', 'Branch Management - Manage Teller Limit'
    UNION ALL SELECT 'BRANCH_MANAGER', 'BRANCH_MANAGEMENT', 'VAULT_MANAGE', 'BRANCH_VAULT_MANAGE', 'Branch Management - Manage Vault'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ATM_CDM', 'CASH_BIN_CREATE', 'ATM_CASH_BIN_CREATE', 'ATM / CDM - Create Cash Bin'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ATM_CDM', 'CASH_BIN_EDIT', 'ATM_CASH_BIN_EDIT', 'ATM / CDM - Edit Cash Bin'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ATM_CDM', 'REPLENISHMENT_CREATE', 'ATM_REPLENISHMENT_CREATE', 'ATM / CDM - Create Replenishment'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ATM_CDM', 'RECONCILIATION_CREATE', 'ATM_RECONCILIATION_CREATE', 'ATM / CDM - Create Reconciliation'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CUSTOMER_MANAGEMENT', 'CREATE', 'CUSTOMER_CREATE', 'Customer Management - Create Customer'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CUSTOMER_MANAGEMENT', 'EDIT', 'CUSTOMER_EDIT', 'Customer Management - Edit Customer'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CUSTOMER_MANAGEMENT', 'ACTIVATE', 'CUSTOMER_ACTIVATE', 'Customer Management - Activate Customer'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CUSTOMER_MANAGEMENT', 'BLOCK', 'CUSTOMER_BLOCK', 'Customer Management - Block Customer'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CUSTOMER_MANAGEMENT', 'ADDRESS_MANAGE', 'CUSTOMER_ADDRESS_MANAGE', 'Customer Management - Manage Customer Address'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CUSTOMER_MANAGEMENT', 'IDENTITY_MANAGE', 'CUSTOMER_IDENTITY_MANAGE', 'Customer Management - Manage Customer Identity'
    UNION ALL SELECT 'BRANCH_MANAGER', 'KYC_MANAGEMENT', 'CREATE', 'KYC_CREATE', 'KYC Management - Create KYC Profile'
    UNION ALL SELECT 'BRANCH_MANAGER', 'KYC_MANAGEMENT', 'EDIT', 'KYC_EDIT', 'KYC Management - Edit KYC Profile'
    UNION ALL SELECT 'BRANCH_MANAGER', 'KYC_MANAGEMENT', 'SUBMIT', 'KYC_SUBMIT', 'KYC Management - Submit KYC Profile'
    UNION ALL SELECT 'BRANCH_MANAGER', 'KYC_MANAGEMENT', 'VERIFY', 'KYC_VERIFY', 'KYC Management - Verify KYC Profile'
    UNION ALL SELECT 'BRANCH_MANAGER', 'KYC_MANAGEMENT', 'DOCUMENT_UPLOAD', 'KYC_DOCUMENT_UPLOAD', 'KYC Management - Upload KYC Document'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ACCOUNT_MANAGEMENT', 'REQUEST_CREATE', 'ACCOUNT_REQUEST_CREATE', 'Account Management - Create Account Opening Request'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ACCOUNT_MANAGEMENT', 'REQUEST_EDIT', 'ACCOUNT_REQUEST_EDIT', 'Account Management - Edit Account Opening Request'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ACCOUNT_MANAGEMENT', 'REQUEST_SUBMIT', 'ACCOUNT_REQUEST_SUBMIT', 'Account Management - Submit Account Opening Request'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ACCOUNT_MANAGEMENT', 'REQUEST_VERIFY', 'ACCOUNT_REQUEST_VERIFY', 'Account Management - Verify Account Opening Request'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ACCOUNT_MANAGEMENT', 'ACCOUNT_ACTIVATE', 'ACCOUNT_ACTIVATE', 'Account Management - Activate Account'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ACCOUNT_MANAGEMENT', 'ACCOUNT_BLOCK', 'ACCOUNT_BLOCK', 'Account Management - Block Account'
    UNION ALL SELECT 'BRANCH_MANAGER', 'ACCOUNT_MANAGEMENT', 'ACCOUNT_FREEZE', 'ACCOUNT_FREEZE', 'Account Management - Freeze Account'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CARD_MANAGEMENT', 'CREATE', 'CARD_CREATE', 'Card Management - Create Card'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CARD_MANAGEMENT', 'EDIT', 'CARD_EDIT', 'Card Management - Edit Card'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CARD_MANAGEMENT', 'ACTIVATE', 'CARD_ACTIVATE', 'Card Management - Activate Card'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CARD_MANAGEMENT', 'BLOCK', 'CARD_BLOCK', 'Card Management - Block Card'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CARD_MANAGEMENT', 'UNBLOCK', 'CARD_UNBLOCK', 'Card Management - Unblock Card'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CARD_MANAGEMENT', 'RENEW', 'CARD_RENEW', 'Card Management - Renew Card'
    UNION ALL SELECT 'BRANCH_MANAGER', 'CARD_MANAGEMENT', 'PIN_EVENT', 'CARD_PIN_EVENT', 'Card Management - Record Card PIN Event'
    UNION ALL SELECT 'BRANCH_MANAGER', 'STATEMENTS', 'CUSTOMER_REQUEST', 'STATEMENT_CUSTOMER_REQUEST', 'Statements - Request Customer Statement'
    UNION ALL SELECT 'BRANCH_MANAGER', 'STATEMENTS', 'BRANCH_REQUEST', 'STATEMENT_BRANCH_REQUEST', 'Statements - Request Branch Statement'
    UNION ALL SELECT 'BRANCH_MANAGER', 'FINANCING', 'APPLICATION_CREATE', 'FINANCING_APPLICATION_CREATE', 'Financing - Create Financing Application'
    UNION ALL SELECT 'BRANCH_MANAGER', 'FINANCING', 'APPLICATION_EDIT', 'FINANCING_APPLICATION_EDIT', 'Financing - Edit Financing Application'
    UNION ALL SELECT 'BRANCH_MANAGER', 'FINANCING', 'APPLICATION_SUBMIT', 'FINANCING_APPLICATION_SUBMIT', 'Financing - Submit Financing Application'

    UNION ALL SELECT 'TELLER', 'CUSTOMER_MANAGEMENT', 'CREATE', 'CUSTOMER_CREATE', 'Customer Management - Create Customer'
    UNION ALL SELECT 'TELLER', 'CUSTOMER_MANAGEMENT', 'EDIT', 'CUSTOMER_EDIT', 'Customer Management - Edit Customer'
    UNION ALL SELECT 'TELLER', 'CUSTOMER_MANAGEMENT', 'ADDRESS_MANAGE', 'CUSTOMER_ADDRESS_MANAGE', 'Customer Management - Manage Customer Address'
    UNION ALL SELECT 'TELLER', 'CUSTOMER_MANAGEMENT', 'IDENTITY_MANAGE', 'CUSTOMER_IDENTITY_MANAGE', 'Customer Management - Manage Customer Identity'
    UNION ALL SELECT 'TELLER', 'ACCOUNT_MANAGEMENT', 'REQUEST_CREATE', 'ACCOUNT_REQUEST_CREATE', 'Account Management - Create Account Opening Request'
    UNION ALL SELECT 'TELLER', 'ACCOUNT_MANAGEMENT', 'REQUEST_EDIT', 'ACCOUNT_REQUEST_EDIT', 'Account Management - Edit Account Opening Request'
    UNION ALL SELECT 'TELLER', 'ACCOUNT_MANAGEMENT', 'REQUEST_SUBMIT', 'ACCOUNT_REQUEST_SUBMIT', 'Account Management - Submit Account Opening Request'
    UNION ALL SELECT 'TELLER', 'STATEMENTS', 'CUSTOMER_REQUEST', 'STATEMENT_CUSTOMER_REQUEST', 'Statements - Request Customer Statement'

    UNION ALL SELECT 'OPERATIONS_OFFICER', 'BRANCH_MANAGEMENT', 'ASSIGN_USER', 'BRANCH_ASSIGN_USER', 'Branch Management - Assign Branch User'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'BRANCH_MANAGEMENT', 'TELLER_LIMIT_MANAGE', 'BRANCH_TELLER_LIMIT_MANAGE', 'Branch Management - Manage Teller Limit'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'BRANCH_MANAGEMENT', 'VAULT_MANAGE', 'BRANCH_VAULT_MANAGE', 'Branch Management - Manage Vault'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ATM_CDM', 'TERMINAL_CREATE', 'ATM_TERMINAL_CREATE', 'ATM / CDM - Create ATM/CDM Terminal'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ATM_CDM', 'TERMINAL_EDIT', 'ATM_TERMINAL_EDIT', 'ATM / CDM - Edit ATM/CDM Terminal'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ATM_CDM', 'CASH_BIN_CREATE', 'ATM_CASH_BIN_CREATE', 'ATM / CDM - Create Cash Bin'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ATM_CDM', 'CASH_BIN_EDIT', 'ATM_CASH_BIN_EDIT', 'ATM / CDM - Edit Cash Bin'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ATM_CDM', 'REPLENISHMENT_CREATE', 'ATM_REPLENISHMENT_CREATE', 'ATM / CDM - Create Replenishment'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ATM_CDM', 'RECONCILIATION_CREATE', 'ATM_RECONCILIATION_CREATE', 'ATM / CDM - Create Reconciliation'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CUSTOMER_MANAGEMENT', 'CREATE', 'CUSTOMER_CREATE', 'Customer Management - Create Customer'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CUSTOMER_MANAGEMENT', 'EDIT', 'CUSTOMER_EDIT', 'Customer Management - Edit Customer'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CUSTOMER_MANAGEMENT', 'ACTIVATE', 'CUSTOMER_ACTIVATE', 'Customer Management - Activate Customer'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CUSTOMER_MANAGEMENT', 'BLOCK', 'CUSTOMER_BLOCK', 'Customer Management - Block Customer'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CUSTOMER_MANAGEMENT', 'ADDRESS_MANAGE', 'CUSTOMER_ADDRESS_MANAGE', 'Customer Management - Manage Customer Address'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CUSTOMER_MANAGEMENT', 'IDENTITY_MANAGE', 'CUSTOMER_IDENTITY_MANAGE', 'Customer Management - Manage Customer Identity'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'KYC_MANAGEMENT', 'CREATE', 'KYC_CREATE', 'KYC Management - Create KYC Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'KYC_MANAGEMENT', 'EDIT', 'KYC_EDIT', 'KYC Management - Edit KYC Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'KYC_MANAGEMENT', 'SUBMIT', 'KYC_SUBMIT', 'KYC Management - Submit KYC Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'KYC_MANAGEMENT', 'VERIFY', 'KYC_VERIFY', 'KYC Management - Verify KYC Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'KYC_MANAGEMENT', 'APPROVE', 'KYC_APPROVE', 'KYC Management - Approve KYC Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'KYC_MANAGEMENT', 'REJECT', 'KYC_REJECT', 'KYC Management - Reject KYC Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'KYC_MANAGEMENT', 'RETURN', 'KYC_RETURN', 'KYC Management - Return KYC Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'KYC_MANAGEMENT', 'DOCUMENT_UPLOAD', 'KYC_DOCUMENT_UPLOAD', 'KYC Management - Upload KYC Document'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CARD_MANAGEMENT', 'CREATE', 'CARD_CREATE', 'Card Management - Create Card'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CARD_MANAGEMENT', 'EDIT', 'CARD_EDIT', 'Card Management - Edit Card'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CARD_MANAGEMENT', 'ACTIVATE', 'CARD_ACTIVATE', 'Card Management - Activate Card'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CARD_MANAGEMENT', 'BLOCK', 'CARD_BLOCK', 'Card Management - Block Card'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CARD_MANAGEMENT', 'UNBLOCK', 'CARD_UNBLOCK', 'Card Management - Unblock Card'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CARD_MANAGEMENT', 'REPLACE', 'CARD_REPLACE', 'Card Management - Replace Card'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CARD_MANAGEMENT', 'RENEW', 'CARD_RENEW', 'Card Management - Renew Card'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'CARD_MANAGEMENT', 'PIN_EVENT', 'CARD_PIN_EVENT', 'Card Management - Record Card PIN Event'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'PROFIT_MANAGEMENT', 'RATIO_CREATE', 'PROFIT_RATIO_CREATE', 'Profit Management - Create Profit Ratio'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'PROFIT_MANAGEMENT', 'RATIO_EDIT', 'PROFIT_RATIO_EDIT', 'Profit Management - Edit Profit Ratio'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'PROFIT_MANAGEMENT', 'SCHEDULE_CREATE', 'PROFIT_SCHEDULE_CREATE', 'Profit Management - Create Profit Schedule'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'PROFIT_MANAGEMENT', 'POSTING_RUN', 'PROFIT_POSTING_RUN', 'Profit Management - Run Profit Posting'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'STATEMENTS', 'CUSTOMER_REQUEST', 'STATEMENT_CUSTOMER_REQUEST', 'Statements - Request Customer Statement'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'STATEMENTS', 'BRANCH_REQUEST', 'STATEMENT_BRANCH_REQUEST', 'Statements - Request Branch Statement'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'NOTIFICATION_ALERTS', 'TEMPLATE_CREATE', 'NOTIFICATION_TEMPLATE_CREATE', 'Notification & Alerts - Create Notification Template'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'NOTIFICATION_ALERTS', 'TEMPLATE_EDIT', 'NOTIFICATION_TEMPLATE_EDIT', 'Notification & Alerts - Edit Notification Template'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'NOTIFICATION_ALERTS', 'EVENT_RULE_CREATE', 'NOTIFICATION_EVENT_RULE_CREATE', 'Notification & Alerts - Create Notification Event Rule'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'NOTIFICATION_ALERTS', 'RETRY', 'NOTIFICATION_RETRY', 'Notification & Alerts - Retry Notification Delivery'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'VERIFICATION', 'SEND_EMAIL_OTP', 'VERIFICATION_SEND_EMAIL_OTP', 'Verification - Send Email Verification OTP'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'VERIFICATION', 'SEND_MOBILE_OTP', 'VERIFICATION_SEND_MOBILE_OTP', 'Verification - Send Mobile Verification OTP'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'VERIFICATION', 'VERIFY_OTP', 'VERIFICATION_VERIFY_OTP', 'Verification - Verify OTP'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'VERIFICATION', 'RESEND_OTP', 'VERIFICATION_RESEND_OTP', 'Verification - Resend OTP'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'VERIFICATION', 'PROVIDER_TEST', 'VERIFICATION_PROVIDER_TEST', 'Verification - Run Verification Provider Test'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ZAKAT_CHARITY', 'PROFILE_CREATE', 'ZAKAT_PROFILE_CREATE', 'Zakat & Charity - Create Zakat Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ZAKAT_CHARITY', 'PROFILE_EDIT', 'ZAKAT_PROFILE_EDIT', 'Zakat & Charity - Edit Zakat Profile'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ZAKAT_CHARITY', 'BENEFICIARY_CREATE', 'CHARITY_BENEFICIARY_CREATE', 'Zakat & Charity - Create Charity Beneficiary'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ZAKAT_CHARITY', 'BENEFICIARY_EDIT', 'CHARITY_BENEFICIARY_EDIT', 'Zakat & Charity - Edit Charity Beneficiary'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ZAKAT_CHARITY', 'BENEFICIARY_ARCHIVE', 'CHARITY_BENEFICIARY_ARCHIVE', 'Zakat & Charity - Archive Charity Beneficiary'
    UNION ALL SELECT 'OPERATIONS_OFFICER', 'ZAKAT_CHARITY', 'BENEFICIARY_RESTORE', 'CHARITY_BENEFICIARY_RESTORE', 'Zakat & Charity - Restore Charity Beneficiary'

    UNION ALL SELECT 'INVESTMENT_OFFICER', 'CALCULATION_ENGINE', 'SIMULATE', 'CALCULATION_SIMULATE', 'Calculation Engine - Run Calculation Simulation'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'ACCOUNT_MANAGEMENT', 'REQUEST_CREATE', 'ACCOUNT_REQUEST_CREATE', 'Account Management - Create Account Opening Request'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'ACCOUNT_MANAGEMENT', 'REQUEST_EDIT', 'ACCOUNT_REQUEST_EDIT', 'Account Management - Edit Account Opening Request'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'ACCOUNT_MANAGEMENT', 'REQUEST_SUBMIT', 'ACCOUNT_REQUEST_SUBMIT', 'Account Management - Submit Account Opening Request'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'ACCOUNT_MANAGEMENT', 'REQUEST_VERIFY', 'ACCOUNT_REQUEST_VERIFY', 'Account Management - Verify Account Opening Request'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'ACCOUNT_MANAGEMENT', 'REQUEST_APPROVE', 'ACCOUNT_REQUEST_APPROVE', 'Account Management - Approve Account Opening Request'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'ACCOUNT_MANAGEMENT', 'REQUEST_REJECT', 'ACCOUNT_REQUEST_REJECT', 'Account Management - Reject Account Opening Request'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'ACCOUNT_MANAGEMENT', 'REQUEST_RETURN', 'ACCOUNT_REQUEST_RETURN', 'Account Management - Return Account Opening Request'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'DEPOSIT_SCHEMES', 'SCHEME_CREATE', 'DEPOSIT_SCHEME_CREATE', 'Deposit Schemes - Create Deposit Scheme'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'DEPOSIT_SCHEMES', 'SCHEME_EDIT', 'DEPOSIT_SCHEME_EDIT', 'Deposit Schemes - Edit Deposit Scheme'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'DEPOSIT_SCHEMES', 'SCHEME_ARCHIVE', 'DEPOSIT_SCHEME_ARCHIVE', 'Deposit Schemes - Archive Deposit Scheme'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'DEPOSIT_SCHEMES', 'SCHEME_RESTORE', 'DEPOSIT_SCHEME_RESTORE', 'Deposit Schemes - Restore Deposit Scheme'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'DEPOSIT_SCHEMES', 'ENROLLMENT_CREATE', 'DEPOSIT_SCHEME_ENROLLMENT_CREATE', 'Deposit Schemes - Create Deposit Scheme Enrollment'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'FINANCING', 'PRODUCT_CREATE', 'FINANCING_PRODUCT_CREATE', 'Financing - Create Financing Product'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'FINANCING', 'PRODUCT_EDIT', 'FINANCING_PRODUCT_EDIT', 'Financing - Edit Financing Product'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'FINANCING', 'PRODUCT_ARCHIVE', 'FINANCING_PRODUCT_ARCHIVE', 'Financing - Archive Financing Product'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'FINANCING', 'PRODUCT_RESTORE', 'FINANCING_PRODUCT_RESTORE', 'Financing - Restore Financing Product'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'FINANCING', 'APPLICATION_CREATE', 'FINANCING_APPLICATION_CREATE', 'Financing - Create Financing Application'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'FINANCING', 'APPLICATION_EDIT', 'FINANCING_APPLICATION_EDIT', 'Financing - Edit Financing Application'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'FINANCING', 'APPLICATION_SUBMIT', 'FINANCING_APPLICATION_SUBMIT', 'Financing - Submit Financing Application'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'FINANCING', 'DISBURSE', 'FINANCING_DISBURSE', 'Financing - Disburse Financing'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'PROFIT_MANAGEMENT', 'RATIO_CREATE', 'PROFIT_RATIO_CREATE', 'Profit Management - Create Profit Ratio'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'PROFIT_MANAGEMENT', 'RATIO_EDIT', 'PROFIT_RATIO_EDIT', 'Profit Management - Edit Profit Ratio'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'PROFIT_MANAGEMENT', 'RATIO_ARCHIVE', 'PROFIT_RATIO_ARCHIVE', 'Profit Management - Archive Profit Ratio'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'PROFIT_MANAGEMENT', 'RATIO_RESTORE', 'PROFIT_RATIO_RESTORE', 'Profit Management - Restore Profit Ratio'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'PROFIT_MANAGEMENT', 'SCHEDULE_CREATE', 'PROFIT_SCHEDULE_CREATE', 'Profit Management - Create Profit Schedule'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'PROFIT_MANAGEMENT', 'SCHEDULE_ARCHIVE', 'PROFIT_SCHEDULE_ARCHIVE', 'Profit Management - Archive Profit Schedule'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'PROFIT_MANAGEMENT', 'SCHEDULE_RESTORE', 'PROFIT_SCHEDULE_RESTORE', 'Profit Management - Restore Profit Schedule'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'PROFIT_MANAGEMENT', 'POSTING_RUN', 'PROFIT_POSTING_RUN', 'Profit Management - Run Profit Posting'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'CONTRACTS', 'TEMPLATE_CREATE', 'CONTRACT_TEMPLATE_CREATE', 'Contracts - Create Contract Template'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'CONTRACTS', 'TEMPLATE_EDIT', 'CONTRACT_TEMPLATE_EDIT', 'Contracts - Edit Contract Template'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'CONTRACTS', 'TEMPLATE_ARCHIVE', 'CONTRACT_TEMPLATE_ARCHIVE', 'Contracts - Archive Contract Template'
    UNION ALL SELECT 'INVESTMENT_OFFICER', 'CONTRACTS', 'TEMPLATE_RESTORE', 'CONTRACT_TEMPLATE_RESTORE', 'Contracts - Restore Contract Template'

    UNION ALL SELECT 'CUSTOMER', 'STATEMENTS', 'CUSTOMER_REQUEST', 'STATEMENT_CUSTOMER_REQUEST', 'Statements - Request Customer Statement'
    UNION ALL SELECT 'CUSTOMER', 'DEPOSIT_SCHEMES', 'ENROLLMENT_CREATE', 'DEPOSIT_SCHEME_ENROLLMENT_CREATE', 'Deposit Schemes - Create Deposit Scheme Enrollment'
    UNION ALL SELECT 'CUSTOMER', 'ZAKAT_CHARITY', 'PROFILE_CREATE', 'ZAKAT_PROFILE_CREATE', 'Zakat & Charity - Create Zakat Profile'
    UNION ALL SELECT 'CUSTOMER', 'ZAKAT_CHARITY', 'PROFILE_EDIT', 'ZAKAT_PROFILE_EDIT', 'Zakat & Charity - Edit Zakat Profile'
) seed
    ON seed.role_code = r.code
LEFT JOIN role_permission rp
    ON rp.role_id = r.id
   AND UPPER(rp.permission_code) = seed.permission_code
WHERE rp.id IS NULL;

SELECT r.code, COUNT(rp.id) AS permission_count
FROM roles r
LEFT JOIN role_permission rp ON rp.role_id = r.id
GROUP BY r.code
ORDER BY r.code;
